name: Auto Assign and Unassign Issues

permissions:
  issues: write  # Ensure the workflow has permission to write to issues

on:
  issues:
    types: [opened, reopened]  # Trigger on issue creation and reopening
  schedule:
    - cron: '0 0 * * 0' # Unassign workflow runs weekly

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check if the issue has specific labels
      - name: Check if issue uses specific labels
        id: label-check
        run: |
          # Check if the issue labels contain 'bug', 'test', or 'enhancement'
          label_matches=false
          for label in "${{ github.event.issue.labels }}"; do
            if [[ "$label" == "bug" || "$label" == "test" || "$label" == "enhancement" ]]; then
              label_matches=true
              break
            fi
          done
          echo "template_matched=$label_matches" >> $GITHUB_ENV

      # Step 2: Check if issue creator is a collaborator
      - name: Check if issue creator is a collaborator
        id: collaborator-check
        if: env.template_matched == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: collaborators } = await github.repos.listCollaborators({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const creator = context.payload.issue.user.login;
            const isCollaborator = collaborators.some(collaborator => collaborator.login === creator);
            return isCollaborator;

      # Step 3: Assign issue to creator if not a collaborator
      - name: Assign issue to creator if not a collaborator
        if: steps.collaborator-check.outputs.result == 'false' && env.template_matched == 'true'
        uses: actions-ecosystem/action-add-issue-assigner@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.event.issue.user.login }}

  auto-unassign:
    runs-on: ubuntu-latest
    steps:
      # Step 4: Unassign issues with no activity for a week
      - name: Unassign issues with no activity for a week
        uses: ahmadnassri/action-unassign-issues@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          inactivity_days: 7
